TRIPARTITE_REPORT_HEADER = [
    'S/No.',
    'Brokers Ref',
    'Client Ref',
    'Material',
    'Bank',
    'Form M to Bank',
    'Form M validated by bank',
    'Form M registered by NCS',
    'Delay Impact',
    'Beneficiary',
    'LC Number',
    'Form m number',
    'Curr',
    'Form m Value',
    'Paymt mode',
    'Comment',
    'FECD SUBMITTED',
    'FECD ACK COPY SENT TO GN',
    'Date P.O /Approved LOA to Broker',
    'Transaction type',
    'Form M application to bank',
    'Form M approved by Customs',
    'LC draft shared with supplier',
    'LC draft vetted by supplier',
    'Final telex received from  bank',
    'Final LC telex / Form M sent to supplier'
]

MICRO_DAILY_REPORT_HEADER = [
    'Country',
    'Type of KPI',
    'Type of Process',
    'Stakeholders',
    'Code of Reason',
    'Month - P',
    'Fiscal week - Diageo',
    'Clearing Agent',
    'How many clearances impacted',
    'PO reference',
    'Supplier Name',
    'Type of material',
    'Start date of Demurrage \nfree time (Berth)',
    'End date of demurrage free time',
    'Estimated value of Demurrage in Nairas',
    'Start date of port charges (Berth + 3days)',
    'End date of port charges (Gate out)',
    'Estimated value of Port charges in Nairas',
    'Penalty Value',
    'Total costs paid',
    'Root Cause Analyzes',
    'Mitigation Plan took to solve the problem',
    'Status of the action',
    'CUSTOM RELEASE DATE',
    'TDO',
    'DELIVERY COMPLETE DATE (offloaded)'
]

MONTHLY_INVOICING_REPORT_HEADER = [
    'File Ref',
    'PO Ref',
    'Client Ref',
    'Conf Dt',
    'Invoice Dt',
    'Supplier Name',
    'Goods Description',
    '20"',
    '40"',
    'Kgs',
    'Units',
    'CNF Value',
    'CUR',
    'Duty',
    'Port Levy',
    'CISS',
    'ETLS',
    'Excise / SPl Levy',
    'VAT on Duty',
    'Terminal Charges',
    'Terminal Rent',
    'Shipping Line Charges',
    'Shipping Dem',
    'Provisional Dem',
    'Container deposit',
    'Airport Charges',
    'Truck Dem',
    'NESREA / NASSIMA / Practitioner fee',
    'QUARANTINE',
    'SON',
    'NAFDAC',
    'Brokers Fee',
    'Agency Fee / Fastrack',
    'Insurance',
    'Transport',
    'Finance Cost',
    'Acc Main. Fee',
    'VAT',
    'Total',
    'C Number',
    'Mode of Clearing',
]


ACTIVITY_REPORT_HEADERS = {
    'QUOTATION_AWAIT_APPROVAL': [
        "S/N",
        "Brokers Reference",
        "Client Reference",
        "Description",
        "Quantity",
        "C&F",
        "Currency",
        "Request Received",
        "Quote Sent",
        "Comment"
    ],
    'AWAITING_SHIPMENT': [
        "S/N",
        "Broker's Reference",
        "Client Reference",
        "Description",
        "Quantity",
        "LOA Date",
        "Form M number",
        "Form M Applied",
        "Form M to supplier",
        "ETD",
        "ETA",
        "Vessel",
        "Shipping line",
        "POD",
        "Comments"
    ],
    'AWAITING_ARRIVAL': [
        "S/N",
        "Broker's Reference",
        "Client Reference",
        "Description",
        "Quantity",
        "Departed",
        "ETA",
        "Vessel",
        "Shipping line",
        "POD",
        "Copy Document Date",
        "Doc Received",
        "Orig docu to bank",
        "PAAR",
        "duty receipt",
        "Nafdac Stamp",
        "Comments"
    ],
    'ARRIVED_IN_CLEARING': [
        "S/N",
        "Broker's Reference",
        "Client Reference",
        "Description",
        "Quantity",
        "Berth",
        "POD",
        "Duty receipt",
        "Nafdac Stamp",
        "Importer's copy",
        "Exam started",
        "Shipping line release",
        "Customs release",
        "TDO",
        "Delivery instruction",
        "Delivery started",
        "Delivery completed",
        "Comments"
    ],
    'DELIVERED_NOT_INVOICED': [
        "S/N",
        "Broker's Reference",
        "Client Reference",
        "Description",
        "Quantity",
        "POD",
        "Duty receipt",
        "Nafdac Stamp",
        "Importer's copy",
        "Exam started",
        "Shipping line release",
        "Customs release",
        "TDO",
        "Delivery competed",
        "Comments"
    ],
    'ACTIVITY_INVOICING': [
        "S/N",
        "Broker's Reference",
        "Client Reference",
        "Description",
        "Quantity",
        "Delivery completed",
        "Invoice acknowledged",
        "Amount in NGN",
        "Payment Terms",
        "Expected Payment",
        "No of days overdue",
        "POD",
        "Comments"
    ],
}
