{
    "name": "Project Description",
    "summary": "Add a description to projects",
    "version": "1.1.3",
    "category": "Project",
    "website": "https://github.com/OCA/project",
    "author": "Tecnativa, " "C2i Change 2 improve, " "Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "depends": [
        "hr",
        "project",
        "sale_timesheet",
        "product",
        "stock",
        "sale_stock",
        "project_category",
        "purchase",
        "account_accountant",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/task_mail_template.xml",
        "wizard/schedule_item_import_view.xml",
        "views/project_view.xml",
        "views/port_view.xml",
        "views/project_schedule_items_view.xml",
        "views/product_template.xml",
        "views/sale_order_view.xml",
        "views/project_type_view_ext.xml",
        "views/purchase_order_view.xml",
        "views/account_move.xml",
    ],
    "installable": True,
}
