{
    "name": "Libra Payment Process Flow",
    "summary": """Libra Payment Process Flow""",
    "description": """
        Libra Payment Process Flow
    """,
    "author": "Matt O'Bell",
    "website": "http://www.yourcompany.com",
    "version": "1.5.9",
    "depends": [
        "sale",
        "account_accountant",
        "purchase_requisition",
        "hr_payroll_account",
        "sale_management",
        "analytic_enterprise",
        "sale_project",
        "hr_expense",
        "customize_vpcs",
        "hr_holidays",
    ],
    "data": [
        'security/ir.model.access.csv',
        "security/res_group.xml",
        "views/account_move.xml",
        "views/res_partner.xml",
        "data/ir_sequence.xml",
        "data/mail_message_subtype.xml",
        "views/hr_payslip_run.xml",
        "views/sale_order.xml",
        "views/res_bank_account.xml",
        "views/hr_expense_sheet.xml",
        "data/mail_template.xml",
        "report/report_saleorder.xml",
        "views/hr_leave.xml",
    ],
    "license": "LGPL-3",
}
