{
    "name": "Vpcs Project Report",
    "version": "15.0.0.1",
    "summary": "Project Report",
    "category": "Other",
    "description": "Project Report",
    "website": "https://www.vperfectcs.com",
    "author": "VperfectCS",
    "maintainer": "VperfectCS",
    "depends": ["project", "report_xlsx"],
    "data": [
        "security/ir.model.access.csv",
        "wizard/project_report_view.xml",
        "report/report.xml",
    ],
    "qweb": [],
    "license": "LGPL-3",
    "installable": True,
    "application": True,
    "auto_install": False,
}
